apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
  namespace: default
type: Opaque
stringData:
  HOMEPAGE_VAR_SONARR_KEY: "YOUR_SONARR_API_KEY"
  HOMEPAGE_VAR_RADARR_KEY: "YOUR_RADARR_API_KEY"
  HOMEPAGE_VAR_LIDARR_KEY: "YOUR_LIDARR_API_KEY"
  HOMEPAGE_VAR_PROWLARR_KEY: "YOUR_PROWLARR_API_KEY"
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: "YOUR_QBITTORRENT_USERNAME"
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "YOUR_QBITTORRENT_PASSWORD"
  HOMEPAGE_VAR_UNIFI_USERNAME: "YOUR_UNIFI_USERNAME"
  HOMEPAGE_VAR_UNIFI_PASSWORD: "YOUR_UNIFI_PASSWORD"
