services:
  vikunja:
    image: vikunja/vikunja:2.3.0
    env_file: .env
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.burney.network/
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_DATABASE_TYPE: sqlite
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped
    labels:
      - homepage.group=Productivity
      - homepage.name=Vikunja
      - homepage.icon=vikunja.png
      - homepage.href=https://vikunja.burndev.lan
      - homepage.description=Task management
      - homepage.showStats=true
