services:
  stash:
    image: stashapp/stash:latest  # TODO: pin to versioned tag or sha256 digest when available
    restart: unless-stopped
    ports:
      - 9999:9999
    environment:
      - STASH_STASH=/srv/stash
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
      - TZ=America/Chicago
    volumes:
      - ./config:/root/.stash
      - ./metadata:/metadata
      - ./cache:/cache
      - ./blobs:/blobs
      - ./generated:/generated
      - /srv/stash:/srv/stash
      - /srv/burntv/media:/srv/burntv/media
