apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  namespace: tools
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: tools
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:4.96.4
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8443
        livenessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: America/Chicago
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: PASSWORD
        - name: SUDO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: SUDO_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: code-server-data
---
apiVersion: v1
kind: Service
metadata:
  name: code-server-svc
  namespace: tools
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
  - port: 80
    targetPort: 8443
    nodePort: 30082
